<?
/*
 * WARNING: DO NOT MODIFY THIS FILE
 * (unless you know what you are doing)
 * 
 * This file is automatically generated by Osimo and tampering
 * with it by hand could potentially cause issues.
 */

###### BEGIN AUTO GENERATED CONTENT ######
$config = array(
	'site_folder' => '/dev/osimo2',
	'database' => array(
		'host' => 'localhost',
		'user' => 'user',
		'password' => 'password',
		'name' => 'osimo'
	),
	'cache' => array(
		'type' => false,
		'prefix' => '',
		'servers' => array(
			'localhost:11211'
		)
	),
	'debug' => array(
		'OsimoDB' => array(
			'events' => true,
			'queries' => true,
			'benchmarking' => true
		),
		'OsimoCache' => array(
			'events' => true
		),
		'OsimoData' => array(
			'events' => true
		),
		'OsimoBBParser' => array(
			'events' => false,
			'benchmarking' => true
		),
		'OsimoUser' => array(
			'events' => true,
			'benchmarking' => true
		)
	),
	'debugOptions' => array(
		"debugVisibility"=>true,
		"disableDebug"=>false
	)
);
###### END AUTO GENERATED CONTENT ######

include('loader.php');
?>