<?
		/*
		 * WARNING: DO NOT MODIFY THIS FILE
		 * (unless you know what you are doing)
		 * 
		 * This file is automatically generated by Osimo and tampering
		 * with it by hand could potentially cause issues.
		 */
		
		###### BEGIN AUTO GENERATED CONTENT ######
$config = 	array(
	'database' => 
	array(
	'name' => 'osimo',
	'username' => 'user',
	'password' => 'password',
	'host' => 'localhost'
	),
	'cache' => 
	array(
	'addresses' => 
	array(
	0 => 'localhost:11211'
	),
	'prefix' => 'osimo'
	),
	'site_folder' => '/osimo/'
	);
###### END AUTO GENERATED CONTENT ######

		include('loader.php');
		?>